stages:
  fetch:
    cmd: uv run python src/data/fetch_data.py
    deps:
      - src/data/fetch_data.py
    params:
      - fetch.raw_dir
    outs:
      - data/raw/_combined.csv:
          persist: true
    always_changed: true

  preprocess:
    cmd: uv run python src/data/preprocess_data.py
    deps:
      - src/data/preprocess_data.py
      - data/raw/_combined.csv
    params:
      - preprocess
    outs:
      - data/preprocessed/flights.csv:
          persist: true

  validate:
    cmd: cd gx && uv run python run_checkpoint.py
    deps:
      - data/preprocessed/flights.csv
    outs:
      - gx/uncommitted:
          persist: true

  test_data:
    cmd: uv run python src/data/test_data.py
    deps:
      - data/preprocessed/flights_reference.csv
      - data/preprocessed/flights_current.csv
      - src/data/test_data.py
    outs:
      - data/reference:
          persist: true
      - reports/drift_report.html:
          persist: true

  train:
    cmd: uv run python src/model/train.py
    deps:
      - src/model/preprocess.py
      - src/model/train.py
      - data/preprocessed/flights.csv
      - gx/uncommitted
      - data/reference
    params:
      - train
    outs:
      - models:
          persist: true