fetch:
  raw_dir: "data/raw"
  year_months:
    - { year: 2024, month: 1 }
    - { year: 2024, month: 2 }
    - { year: 2024, month: 3 }
    - { year: 2024, month: 4 }
    - { year: 2024, month: 5 }
    - { year: 2024, month: 6 }
    - { year: 2024, month: 7 }
    - { year: 2024, month: 8 }
    - { year: 2024, month: 9 }
    - { year: 2024, month: 10 }
    - { year: 2024, month: 11 }
    - { year: 2024, month: 12 }
    # for drift detection
    - { year: 2025, month: 1 }


preprocess:
  output_path: "data/preprocessed/flights.csv"
  drop_cancelled: true
  drop_diverted: true
  reference_year: 2024
  current_year: 2025

train:
  test_size: 0.2
  random_state: 42
  target_col: "DepDelayMinutes"
  n_estimators: 500
  max_depth: 8
  learning_rate: 0.05
  subsample: 0.8
  sample_size: 1000000